webdriver.driver=chrome
chrome.switches=--start-maximized,--disable-notifications,--remote-allow-origins=*
serenity.project.name=Automatizacion Web Bon-Bonite
webdriver.autodownload=true

webdriver.timeouts.implicitlywait=10000
serenity.restart.browser.for.each = example
serenity.maintain.session = false
serenity.verbose.steps=false
serenity.report.encoding=UTF8
feature.file.encoding=UTF8
serenity.reports.show.step.details=true
serenity.browser.maximized=true
serenity.browser.disable-notifications=true
serenity.outputDirectory = target/site/serenity